### ISSUE TITLE
Usage Guide

### ISSUE THREAD

**Issue by Tejas-R-Pattar** [imrun10/ML-Loan-Default#1]
It would be very help if you provide a guide on how to use this project.

**Comment by imrun10** [comment]
Greetings,

Thank you for your message, to make the code work, you must:
- Upload the codes and dataset (test.csv) on MATLAB (sampleSubmission.csv is merely a sample submission of our work).
- Run the codes in the following order: Quality_report.m, Normalise_data.m and then Tables.m.
- Run the models in the classification learner app on MATLAB 10 times, and tabulate the results for each execution on Excel.
- Run Boxplots.m with the tabulated results from Excel.
Refer to the poster for more details and thank you.
